name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go 1.21
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Download dependencies
      run: go mod tidy
  
    - name: Build
      run: go build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_SSH_USER }}
        key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
        script: |
          cd bansosplus-backend
          git pull --ff-only
          kill $(lsof -t -i:8001)
          nohup go run server.go > server.log 2>&1 &